#ifndef KD2CONSTANTS_H
#define KD2CONSTANTS_H

enum LogLevel { ERROR, INFORMATION, DEBUG};

const int KD2_MPI_MASTER	=	0;
const int KD2_MPI_BCAST		=	-2;

enum MPICommand { NULL_COMMAND, START, START_SECTION, FINISH_SECTION, PAUSE, RESUME, END};

#endif // KD2CONSTANTS_H
